Security 3190
jenkinsci/tap-plugin pull request #37
Opened 2024-01-19 09:47 UTC by kinow

Note: Security issues are normally handled in private. Do not use this pull request as an example of how to tackle security issues. This PR is public as the security bug was published in a Jenkins security advisory (there is a deadline for security bugs to be fixed, and this one did not reach it).

I wrote a test case to reproduce the issue. I used an existing test from the Active Choices Plug-in, which made it super easy to reproduce the bug with JUnit. The second command expands the example payload to try to inject the XSS payload in more parts of the TAP Stream.

The review is happening here and in the security issue (which is still private, I think). Again, do not use this PR as reference for future work. 

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-01-19 09:53 UTC, kinow commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> -                sb.append("</tr>");
The old code had some duplication, and that meant we would have to fix it on both ends of the `if` statement. The part below is the simplified code. I will highlight where the fix was applied as suggested by the issue reporter.

2024-01-19 09:53 UTC, kinow commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +            sb.append("<td style=\"width: auto;\">").append(StringEscapeUtils.escapeHtml(key)).append("</td>");
Escaped :point_up:

2024-01-19 09:53 UTC, kinow commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +                        StringEscapeUtils.escapeHtml(fileName),
Escaped :point_up:

2024-01-19 09:53 UTC, kinow commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +                sb.append("<td><pre>").append(org.apache.commons.lang.StringEscapeUtils.escapeHtml(value.toString())).append("</pre></td>");
I will update the import here later as there's no need to use the fully qualified name with the import added :point_up:

2024-01-19 09:53 UTC, kinow commented on src/test/java/org/tap4j/plugin/jenkins_cert_3190/TestXssTapFile.java
> +                false,
IDE's like IntelliJ show the name of each variable. This one is to show only failed tests. If enabled, the given payload is not displayed. Thus the payload duplicated above for a `not ok 2` :+1:

2024-01-22 12:24 UTC, yaroslavafenkin requested changes

2024-01-22 12:24 UTC, yaroslavafenkin commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +                        StringEscapeUtils.escapeHtml(tapFile),
`StringEscapeUtils.escapeHtml` won't escape single quote, and hence is not good enough, as we're in context of an attribute. 
I'd recommend looking at https://github.com/jenkinsci/jenkins/blob/c48728d0f49840d7eb7e1b4e4e2edc33753bd914/core/src/main/java/hudson/Functions.java#L842-L864.

2024-01-22 21:39 UTC, kinow commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +                        StringEscapeUtils.escapeHtml(tapFile),
Found the old issue in Commons Lang about this, but I had no memory of working on that. https://issues.apache.org/jira/browse/LANG-1042

I tried to add a test where the single quote caused the current code to fail filtering for it, but I think Jenkins might be doing some escaping somewhere after the file is read from disk, and before it reaches the HTML attribute. So I ended up just replacing the `StringEscapeUtils.escapeHtml` by `Functions.htmlAttributeEscape` where attributes we being used.

2024-01-23 15:15 UTC, yaroslavafenkin commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +                        Functions.htmlAttributeEscape(tapFile),
Following up here.
In case you decide to go with double escaping you'd ideally have test coverage to make sure there's no alert, and also that legit use cases aren't broken by that.

2024-01-27 08:42 UTC, kinow commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +                        Functions.htmlAttributeEscape(tapFile),
Hi. Sorry, I had a few things at work that prevented me from progressing here. Just had a look at your previous two comments, and looks like this is not that simple. I will try to find a large time slot to understand well this  part of XSS an d attributes, and the double escaping here, then work on the fix + test coverage. Thanks for the review @yaroslavafenkin !

2024-03-29 17:41 UTC, kinow commented on src/main/java/org/tap4j/plugin/util/DiagnosticUtil.java
> +                        Functions.htmlAttributeEscape(tapFile),
I added a new build step with @yaroslavafenkin 's example above

![image](https://github.com/jenkinsci/tap-plugin/assets/304786/2d2a5006-fc7b-442f-a854-af771f551ae7)

(I updated the pattern to locate and archive the files)

Then triggered a new build, and opened the pages with the plugin actions. None triggered the `alert`. Not even the TAP Extended Results.

![image](https://github.com/jenkinsci/tap-plugin/assets/304786/702ffab7-0815-44cb-9b20-17d8a4a09142)

So I guess the current code is not affected and we can resolve this thread.

2024-03-29 17:41 UTC, kinow commented
Tested on Chromium and Firefox and I couldn't trigger an `alert` with the current code. Mind having another look, please, @yaroslavafenkin ? Thanks!

2024-04-03 11:52 UTC, kinow commented
> LGTM

Thank you for testing this again, @yaroslavafenkin. I also couldn't reproduce it, so hopefully the issue is fixed, and the tests we have will prevent any regression.

Care to have a final look and sign off this PR, @daniel-beck , please? Then I will merge, release, and update the sec issue. Cheers

2024-04-06 09:31 UTC, kinow commented
Going to merge this as I have some time this morning to work on OSS. We can review/re-open the issue later if needed. Thanks all for the help!

2024-04-06 09:31 UTC, merged

2024-04-06 09:56 UTC, kinow commented
In 2.4.2.